### ISSUE TITLE
Mention new repository URL and license

### ISSUE THREAD

**Issue by ju1m** [abhin4v/abhin4v.github.io#300]
**@abhin4v your website's source code is a very pleasant read! Thank you!**

I was happy to see that you're still publishing its source on https://code.abhinavsarkar.net/abhin4v/abhin4v.github.io but this new repository is harder to find because the `README.md` and https://jaspervdj.be/hakyll/examples.html still point to https://github.com/abhin4v/abhin4v.github.io . I can understand your keeping the latter pointing to the old repository now that you're no longer using `Hakyll` but it would be great to mention the new repository somewhere as well.

Also, your `site.cabal` is missing a `license:` field, so I guess that by default all rights are reserved to you and one cannot copy your code legally. Arguably you should also add per file [SPDX](https://spdx.org) comments (eg. using the https://reuse.software) to be as accurate and unambiguous as possible, or it could be as unintrusive as a single `.reuse/dep5` file using file path patterns, example:

```dep5
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: abhinavsarkar.net
Upstream-Contact: Abhinav Sarkar <abhinav@abhinavsarkar.net>
Source: https://code.abhinavsarkar.net/abhin4v/abhin4v.github.io

Files: flake.nix flake.lock cabal.project* *.cabal *.md .chglog/* .envrc .gitignore *.yaml *.yml Dockerfile* robots.txt .dockerignore .gitmodules
Copyright: Abhinav Sarkar <abhinav@abhinavsarkar.net>
License: CC0-1.0

Files: bin/* css/* js/* src/* templates/*
Copyright: Abhinav Sarkar <abhinav@abhinavsarkar.net>
License: AGPL-3.0-or-later

Files: biblio/* code/* files/* images/* posts/* slides/* talks/* 404.html
Copyright: Abhinav Sarkar <abhinav@abhinavsarkar.net>
License: CC-BY-SA-3.0

Files: fonts/*
Copyright: Respective owners
License: OFL-1.1
```

Then run : `reuse download --all` to provision `LICENSES/`, and check the result with:
```shell
$ reuse lint
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: AGPL-3.0-or-later, CC-BY-SA-3.0, CC0-1.0, OFL-1.1
* Read errors: 0
* Files with copyright information: 374 / 374
* Files with license information: 374 / 374

Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)
```

Thanks again.

**Comment by abhin4v** [comment]
The new website code is not meant to be public and I'll make it private some day. Hence, not adding any license.
